name: test_dart_example

environment:
  sdk: '^3.4.0'


dependencies:
  fpdart: ^1.1.1
  collection: ^1.19.1
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
